Resolves HELIO-3613 modify auth API
mlibrary/turnsole pull request #14
Opened 2021-01-25 21:11 UTC by gkostin1966

Added product access API

      #
      # Access { :full, :read, :none }
      #
      #   :full - both read and download access
      #   :read - read access (no download access)
      #   :none - no access, but has subscription
      #
      #   :undefined - no subscription
      #

      test access -> def product_individual_access?(product_identifier:, individual_identifier:, access_type:)
      get access  -> def product_individual_access(product_identifier:, individual_identifier:)
      set access  -> def access_product_individual(product_identifier:, individual_identifier:, access_type:)

      test access -> def product_institution_access?(product_identifier:, institution_identifier:, access_type:)
      get access  -> def product_institution_access(product_identifier:, institution_identifier:)
      set access  -> def access_product_institution(product_identifier:, institution_identifier:, access_type:)

2021-01-26 22:32 UTC, jgmorse requested changes

2021-01-26 22:32 UTC, jgmorse commented on lib/turnsole/heliotrope/service.rb
> +      def access_product_individual(product_identifier:, individual_identifier:, access_type:)
I don't understand the difference between this method and [subscribe_product_individual](https://github.com/mlibrary/turnsole/pull/14/files#diff-b0b53bcfa5d13675f7277c74c07a8fc8b794306004be1c6354ea1d2d6a528cc0R248). 

Is the difference that this method is _changing_ an access type on an existing subscription? Whereas the other method is creating a new subscription and setting its access type?

I think their names need to change to something more illustrative, to make the distinction clearer.

2021-01-26 22:32 UTC, jgmorse commented on lib/turnsole/heliotrope/service.rb
> +      #   :undefined - no subscription
```suggestion
      #   :undefined - no association between subscriber and product
```

2021-01-26 22:32 UTC, jgmorse commented on lib/turnsole/heliotrope/service.rb
> +      #   :none - no access, but has subscription
```suggestion
      #   :none - expired access
```

2021-01-26 22:32 UTC, jgmorse commented on lib/turnsole/heliotrope/service.rb
> +      def access_product_institution(product_identifier:, institution_identifier:, access_type:)
I don't understand the difference between this method and [subscribe_product_institution](https://github.com/mlibrary/turnsole/pull/14/files#diff-b0b53bcfa5d13675f7277c74c07a8fc8b794306004be1c6354ea1d2d6a528cc0R283)

Is the difference that this method is changing an access type on an existing subscription? Whereas the other method is creating a new subscription and setting its access type?

I think their names need to change to something more illustrative, to make the distinction clearer.

2021-03-22 17:29 UTC, sethaj commented
Closing this. The changes will be in https://github.com/mlibrary/turnsole/pull/15  instead.

2021-03-22 17:29 UTC, closed without merging